-- Update existing clients with CSV data
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 544.00, software = 'FreeAgent', recurring_day = 20, contract_start_date = '2026-01-20', key_contact_email = 'ksafari@visiting-angels.co.uk', key_contact_name = 'Kya' WHERE name = 'Visiting Angels';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 1667.40, software = 'FreeAgent', recurring_day = 6, contract_start_date = '2026-01-06', key_contact_email = 'info@sojcare.co.uk', key_contact_name = 'Anthony' WHERE name = 'Springs of Joy';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 380.00, software = 'FreeAgent', recurring_day = 13, contract_start_date = '2026-01-13', key_contact_email = 'info@veronahomecare.co.uk', key_contact_name = 'Beatrice' WHERE name = 'Verona Homecare';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 380.00, software = 'FreeAgent', recurring_day = 18, contract_start_date = '2026-01-18', key_contact_email = 'flo@flowhealthcareservices.co.uk', key_contact_name = 'Florina' WHERE name = 'Flow Healthcare';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 220.50, software = 'Zoho', recurring_day = 8, contract_start_date = '2026-01-08', key_contact_email = 'admin@frontistiservices.org', key_contact_name = 'Nicholas' WHERE name = 'Frontisti Services';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 714.00, software = 'FreeAgent', recurring_day = 28, contract_start_date = '2026-01-28', key_contact_email = 'info@adenhealthcare.co.uk', key_contact_name = 'Frank' WHERE name = 'Aden Healthcare';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 850.00, software = 'FreeAgent', recurring_day = 30, contract_start_date = '2026-01-30', key_contact_email = 'd.nsabagwa@dbamsocialcare.co.uk', key_contact_name = 'Doreen' WHERE name = 'DBAM';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 210.00, software = 'FreeAgent', recurring_day = 24, contract_start_date = '2026-01-24', key_contact_email = 'sholababatunde@mission-health.co.uk', key_contact_name = 'Shola' WHERE name = 'Mission Healthcare';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 3023.00, software = 'FreeAgent', recurring_day = 27, contract_start_date = '2026-01-27', key_contact_email = 'info@lorabloomscare.com', key_contact_name = 'Wura' WHERE name = 'Lorablooms Care Services';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 868.00, software = 'FreeAgent', recurring_day = 16, contract_start_date = '2026-01-16', key_contact_email = 'info@carenestsolutions.co.uk', key_contact_name = 'Joanna' WHERE name = 'Carenest Solutions';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 393.00, software = 'FreeAgent', recurring_day = 4, contract_start_date = '2026-01-04', key_contact_email = 'Alex.dwebeng@ceibraxs.co.uk, info@ceibraxs.co.uk', key_contact_name = 'Alex' WHERE name = 'Ceibraxs';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 2232.36, software = 'FreeAgent', recurring_day = 3, contract_start_date = '2026-01-03', key_contact_email = 'oice.hr@outlook.com', key_contact_name = 'Enock' WHERE name = 'OICE';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 3459.75, software = 'FreeAgent', recurring_day = 26, contract_start_date = '2026-01-26', key_contact_email = 'rsosanya@topaz-support.org.uk', key_contact_name = 'Racheal' WHERE name = 'Topaz Care and Support';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 380.00, software = 'FreeAgent', recurring_day = 12, contract_start_date = '2026-01-12', key_contact_email = 'Info@dictra.co.uk', key_contact_name = 'Sophie' WHERE name = 'DICTRA';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 220.50, software = 'Zoho', recurring_day = 30, contract_start_date = '2026-01-30', key_contact_email = 'alphaglobeltd@hotmail.com', key_contact_name = 'Valerie, Stepanie' WHERE name = 'Alpha Globe';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 704.00, software = 'Zoho', recurring_day = 30, contract_start_date = '2026-01-30', key_contact_email = 'info@careluxsupportservices.com', key_contact_name = 'Idowu' WHERE name = 'Carelux Support Services';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 714.00, software = 'Zoho', recurring_day = 2, contract_start_date = '2026-01-02', key_contact_email = 'Info@winsidecare.co.uk, abby.arowojolu@winsidecare.co.uk', key_contact_name = 'Mrs A' WHERE name = 'Winside Care Services';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 510.00, software = 'FreeAgent', recurring_day = 6, contract_start_date = '2026-01-06', key_contact_email = 'info@icareservicesgroup.co.uk, admin@icareservicesgroup.co.uk', key_contact_name = 'Temi' WHERE name = 'iCareServices';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 224.70, software = 'FreeAgent', recurring_day = 25, contract_start_date = '2026-01-25', key_contact_email = 'james.akindele@brandhealthcare.co.uk', key_contact_name = 'James' WHERE name = 'Brand Healthcare';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 224.70, software = 'FreeAgent', recurring_day = 2, contract_start_date = '2026-01-02', key_contact_email = 'Joyce@jpkhealthcare.co.uk', key_contact_name = 'Joyce' WHERE name = 'JPK';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 909.50, software = 'FreeAgent', key_contact_email = 'tonte.abban@myrtlehealthcare.co.uk, richard.abban@myrtlehealthcare.co.uk', key_contact_name = 'Tonte' WHERE name = 'Myrtle Healthcare';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 406.60, software = 'FreeAgent', key_contact_email = 'info@everychildservices.com' WHERE name = 'Every Child Services';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 545.70, software = 'Zoho', key_contact_email = 'info@carenova.co.uk', key_contact_name = 'Liossa Mudhala', company_address = '1 Emperor Way, Regus, EX1 3QS, Exeter, Devon', website_address = 'https://carenova.co.uk/', software_used = 'Nourish (CarePlanner)', billing_contact_name = 'Carenova Ltd', billing_contact_email = 'info@carenova.co.uk' WHERE name = 'Carenova';
UPDATE public.clients SET source = 'Referral', status = 'active', mrr = 909.50, software = 'FreeAgent', key_contact_email = 'carlton@angelandstarcareservices.com', key_contact_name = 'Carlton Limted', company_address = 'Oakrigde, Weston Road, Stafford, Staffordshire, England, ST16 3RS', website_address = 'https://angelandstarcareservices.com', software_used = 'Log my Care', billing_contact_name = 'Ashley Limted', billing_contact_email = 'accounts@angelandstarcareservices.com' WHERE name = 'Angel and Star Care Services';
UPDATE public.clients SET source = 'N/A', status = 'active', mrr = 400.00, software = 'Zoho', recurring_day = 1, contract_start_date = '2026-02-01', key_contact_email = 'info@best2care.co.uk', key_contact_name = 'BEST2CARE' WHERE name = 'BEST2CARE';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 1360.00, software = 'FreeAgent', recurring_day = 12, contract_start_date = '2026-01-12', key_contact_email = 'rose.o@calvary-care.org.uk', key_contact_name = 'Roseline' WHERE name = 'Calvary Care';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 380.00, software = 'FreeAgent', recurring_day = 3, contract_start_date = '2026-01-03', key_contact_email = 'info@ignitehealthcare.co.uk', key_contact_name = 'Winnie' WHERE name = 'Ignite Healthcare';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 1190.00, software = 'FreeAgent', recurring_day = 21, contract_start_date = '2026-01-21', key_contact_email = 'manager@spring-fountainltd.co.uk', key_contact_name = 'Florence' WHERE name = 'Spring Fountain';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 850.00, software = 'FreeAgent', recurring_day = 21, contract_start_date = '2026-01-21', key_contact_email = 'prash.patel@nursenextdoor.co.uk, karen.patel@nursenextdoor.co.uk', key_contact_name = 'Prash' WHERE name = 'Nurse Next Door';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 909.00, software = 'FreeAgent', key_contact_email = 'patricia@risingcareservices.uk, odell@risingcareservices.uk', key_contact_name = 'Patricia Francis', company_address = 'Regus 4 Penman Way 1st Floor Gateway House, Enderby, Leicester, England, LE19 1SY', website_address = 'https://risingcare.co.uk', software_used = 'Care Planner, Nourish, Roundsys, Care Beans', billing_contact_name = 'Odell Samvura', billing_contact_email = 'admin@risingcareservices.co.uk' WHERE name = 'Rising Care Services';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 545.70, software = 'FreeAgent', key_contact_email = 'olufunke@jandcservicesltd.com', key_contact_name = 'Olufunke Robertson-Jones', company_address = 'Office 10, Highbridge Enterprise Centre, Isleport Business Park, Bennet Road, Highbridge, Somerset. TA9 4AL.', website_address = 'jandchealthcare.com', software_used = 'Carelinelive', billing_contact_name = 'Olufunke Robertson-Jones', billing_contact_email = 'info@jandcservicesltd.com' WHERE name = 'J & C Healthcare';
UPDATE public.clients SET source = 'Tomiwa', status = 'active', mrr = 406.60, software = 'Zoho', key_contact_email = 'registeredmanager@blackhorsecare.com', key_contact_name = 'Augustine Ukandu', company_address = 'Head Office Jhumat House, 160 London Road, Barking, IG11 8BB United Kingdom', website_address = 'https://blackhorsecare.com/', software_used = 'careforit', billing_contact_name = 'Augustine Ukandu', billing_contact_email = 'finance@blackhorsecare.com' WHERE name = 'Blackhorse';
UPDATE public.clients SET source = 'Tik Tok', status = 'active', mrr = 1249.50, software = 'FreeAgent', recurring_day = 8, contract_start_date = '2026-01-08', key_contact_email = 'info@raychantpat.co.uk', key_contact_name = 'Melissa' WHERE name = 'Raychantpat';
UPDATE public.clients SET source = 'Tomiwa', status = 'at_risk', mrr = 1608.00, software = 'FreeAgent', recurring_day = 7, contract_start_date = '2026-01-07', key_contact_email = 'option.careltd@gmail.com', key_contact_name = 'Collins' WHERE name = 'Option Care';
UPDATE public.clients SET source = NULL, status = 'prospect', mrr = NULL, software = 'Zoho', key_contact_email = 'info@brisen.co.uk', key_contact_name = 'Francisca Agwu', company_address = '194 Wricklemarsh Road, Blackheath, London, SE3 8DP', website_address = 'https://ww.brisen.co.uk', software_used = 'Birdie', billing_contact_name = 'Francisca Agwu', billing_contact_email = 'Francisca.agwu@brisen.co.uk' WHERE name = 'Brisen Care';

-- Insert new clients that don't exist
INSERT INTO public.clients (name, source, status, mrr, software, recurring_day, contract_start_date, key_contact_email, key_contact_name, created_by)
VALUES
('Kings Comfort', 'Referral', 'inactive', NULL, 'Zoho', 6, '2026-01-06', 'info@kingscomforthealthcare.co.uk', NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Better Living Care', 'Referral', 'inactive', NULL, 'FreeAgent', 14, '2026-01-14', 'Info@betterlivingcare.co.uk', NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Well Led', 'Email', 'inactive', NULL, 'FreeAgent', 11, '2026-01-11', 'info@wellledcareltd.co.uk', 'Lucy', '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Dr Anthonia', NULL, 'onboarding', NULL, 'FreeAgent', NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Passion Homecare', NULL, 'onboarding', NULL, 'FreeAgent', NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Imoleayo', NULL, 'onboarding', NULL, 'FreeAgent', NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('NKCARE', NULL, 'prospect', NULL, NULL, 30, '2026-01-30', 'mary@nkcare.co.uk', NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Noren Suneram', NULL, 'prospect', NULL, NULL, NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Sussanah - follow up late', NULL, 'prospect', NULL, NULL, NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Ebere - yet to follow up', NULL, 'prospect', NULL, NULL, NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Miriam - victoriousliving.co.uk', NULL, 'prospect', NULL, NULL, NULL, NULL, NULL, NULL, '1bbeda02-fca3-4294-ac57-9d13d1502774'),
('Astonishing care limited', NULL, 'prospect', NULL, 'Zoho', NULL, NULL, 'Carlan200882@gmail.com', 'Carol Ajike', '1bbeda02-fca3-4294-ac57-9d13d1502774');