// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pavwwgfgpykakbqkxsal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdnd3Z2ZncHlrYWticWt4c2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTI0MTgsImV4cCI6MjA2ODI2ODQxOH0.P_bXEqMgMBY3gAb3XX-NXGkFeIhi6w8BFJBPx8Qx0mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Supabase serialises auth/token-refresh across tabs with the Web Locks API.
// Its default waits for the lock forever, so a crashed, duplicated or
// backgrounded tab that holds the auth lock and never releases it makes
// getSession()/refresh block indefinitely — the app then hangs on the loading
// splash. This lock keeps the normal cross-tab coordination but never blocks
// forever: if it can't acquire the lock within a few seconds it runs the auth
// operation anyway (accepting a rare, harmless cross-tab refresh race instead
// of an indefinite hang).
const resilientAuthLock = <R>(name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
  const locks = typeof navigator !== "undefined" ? navigator.locks : undefined;
  if (!locks) return fn();
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 5000);
  return locks
    .request(name, { signal: controller.signal }, async () => {
      clearTimeout(timer);
      return fn();
    })
    .catch((err: unknown) => {
      clearTimeout(timer);
      // Couldn't get the lock in time (a stuck tab is holding it) — proceed
      // without cross-tab coordination rather than hang.
      if (err instanceof DOMException && err.name === "AbortError") return fn();
      throw err;
    }) as Promise<R>;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: resilientAuthLock,
  }
});